spring:
  application:
    name: exchange-api
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:exchangedb
    username: root
    password: password
    driver-class-name: org.h2.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      idle-timeout: 30000
      pool-name: exchange-api
      max-lifetime: 2000000
      connection-timeout: 30000
    type: com.zaxxer.hikari.HikariDataSource
  jackson:
    serialization:
      INDENT_OUTPUT: true
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: non_null
  mvc:
    throw-exception-if-no-handler-found: true


server:
  port: 8080



adapters:
  exchange-rate:
    access-key: 58972f6c2434836056b981372b147c4d
    base-url: http://data.fixer.io/api/latest
    enabled: true
  conversion:
    enabled: true
    access-key: 58972f6c2434836056b981372b147c4d
    base-url: https://api.exchangeratesapi.io/v1/latest
