drop table if exists conversion;
create table conversion
(
    id         bigint generated by default as identity,
    created_at timestamp      not null,
    updated_at timestamp,
    amount     decimal(19, 2) not null,
    source     varchar(10)    not null,
    result     decimal(19, 2) not null,
    target     varchar(10)    not null,
    primary key (id)
);
